/* PETSCII chars to draw text boxes, etc. */
#define CHAR_VERT_LINE 			0x5d
#define CHAR_HORIZ_LINE			0x40
#define CHAR_UPPER_LEFT_CORNER	0x70
#define CHAR_UPPER_RIGHT_CORNER	0x6e
#define CHAR_LOWER_LEFT_CORNER	0x6d
#define CHAR_LOWER_RIGHT_CORNER	0x7d
#define CHAR_RIGHT_JUNCTION		0x6b
#define CHAR_LEFT_JUNCTION		0x73
#define CHAR_4_WAY_JUNCTION 	0x5b

#define CHAR_THICK_UL_CORNER	0xec
#define CHAR_THICK_UR_CORNER	0xfb
#define CHAR_THICK_UPPER_HORIZ	0xe2
#define CHAR_THICK_LOWER_HORIZ	0x62
#define CHAR_THICK_LEFT_VERT	0x61
#define CHAR_THICK_RIGHT_VERT	0xe1

#define CHAR_INVERSE_SPACE		0xa0
